// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/simpleKalvin/geekbang_homework/week04/internal/biz"
	"github.com/simpleKalvin/geekbang_homework/week04/internal/data/goods"
	"github.com/simpleKalvin/geekbang_homework/week04/internal/data/user"
)

// Injectors from wire.go:

func InitOrder(goods_id goods.GoodsId, user_id user.UserId) (biz.Order, error) {
	userUser := user.NewUser(user_id)
	goodsGoods := goods.NewGoods(goods_id)
	order := biz.NewOrder(userUser, goodsGoods)
	return order, nil
}
